### ISSUE TITLE
Support for esp32

### ISSUE THREAD

**Issue by KJPOUNDY132** [arduino-libraries/ArduinoModbus#103]
Hi, is this library support ESP32 or 8266?

**Comment by per1234** [comment]
Hi @KJPOUNDY132. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino-libraries/ArduinoModbus/issues/32.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
