### ISSUE TITLE
Arduino H7 TCP/IP slave connection With MG400 dobot robot

### ISSUE THREAD

**Issue by Freeko84** [arduino-libraries/ArduinoModbus#110]
I have an Arduino H7 board with an Arduino Vision Shield and I want to set up a TCP/IP connection with a Dobot MG400 robot to send the position of objects.  Does anyone have experience with this or can someone help me with this?  I have no experience with Arduino IDE software and I don't know if it is possible to set this up.

Kind regards,

Frederik

**Comment by per1234** [comment]
Hi @Freeko84. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the project. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
