### ISSUE TITLE
Add support for STM32Duino

### ISSUE THREAD

**Issue by rozrabiak** [arduino-libraries/ArduinoModbus#116]
Please add support for USBSerial (Serial1, Serial2) -> STM32F4CCU6.
STM32 support -> BlackPill, BluePill. (STM32Duino)

Thank's

**Comment by per1234** [comment]
Hi @rozrabiak. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino-libraries/ArduinoModbus/issues/47.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
