### ISSUE TITLE
Porting ArduinoModbus Library to Raspberry Pi Pico without Arduino Core

### ISSUE THREAD

**Issue by SonicTS** [arduino-libraries/ArduinoModbus#122]
Hello,

I'm working on a project where I need to run a ModbusRTU Server on my Raspberry Pi Pico. I've chosen to use the ArduinoModbus library, but I'd like to avoid the Arduino core due to its overhead and speed limitations.

I'm aware that the RS485 driver in this library relies on Arduino-specific functions, particularly the HardwareSerial and Stream classes. My objective is to replace these dependencies with their equivalents from the Pico SDK.

Additionally, I've noticed that libmodbus can be built for different platforms like WIN32, Arduino, and others. What would be the best approach to port libmodbus specifically for the Pico? Would I need to implement certain functions from scratch, or can I leverage the existing Arduino port and simply replace the Arduino-specific functions with those from the Pico SDK?

Is there any other aspect of the library's structure or dependencies that I might have overlooked and would need to consider when porting to the Pico?

Any guidance or suggestions would be greatly appreciated. Thank you!

**Comment by per1234** [comment]
Hi @SonicTS. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the project. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
