### ISSUE TITLE
Incorrect conversion of seconds and micro seconds to milliseconds

### ISSUE THREAD

**Issue by r2park** [arduino-libraries/ArduinoModbus#127]
https://github.com/arduino-libraries/ArduinoModbus/blob/0cee633cb267962e1cf0a780b8028e049656b0da/src/libmodbus/modbus-tcp.cpp#L838C62-L838C62

https://github.com/arduino-libraries/ArduinoModbus/blob/0cee633cb267962e1cf0a780b8028e049656b0da/src/libmodbus/modbus-rtu.cpp#L1262

**Comment by facchinm** [comment]
It is correct, since `struct timeval` is defined as https://renenyffenegger.ch/notes/development/languages/C-C-plus-plus/C/libc/structs/timeval . So if you have `tv` defined as ```
