### ISSUE TITLE
How to remove useless PINs in RS485?

### ISSUE THREAD

**Issue by jason-hulkman** [arduino-libraries/ArduinoModbus#138]
I burn the Ameba IoT Arduino into my wifi module realtek 8720DN. I want to use the Audino Modbus lib, but how to set RS485 pins?

I just use the tx/rx to send/receive data, how to remove/disable other useless Pins, like DE, RE pin.

**Comment by per1234** [comment]
Hi @jason-hulkman. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the project. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
