### ISSUE TITLE
Arduino modbus keywords sample codes requset

### ISSUE THREAD

**Issue by pruthuvi96** [arduino-libraries/ArduinoModbus#141]
Can anyone send an article related to arduinomodbus.h library with its keywords and sample code related to keywords

**Comment by per1234** [comment]
Hi @pruthuvi96. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the project. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
