### ISSUE TITLE
Use this library with Sparkfun AST-CAN485

### ISSUE THREAD

**Issue by willwilder** [arduino-libraries/ArduinoModbus#17]
Has anybody had success getting this library to work with the Sparkfun device? Can't figure out how to configure the DE and RE pins

**Comment by sandeepmistry** [comment]
Hi @willwilder,

We haven't tested this library with that board. However, you can refer to the following page on how to change the pins: https://www.arduino.cc/en/RS485/SetPins

That function is in the `RS485` library which this library depends on.
