### ISSUE TITLE
`ModbusServer::writeInputRegisters` not implemented

### ISSUE THREAD

**Issue by jlucas2019** [arduino-libraries/ArduinoModbus#18]
Hello,

When trying to use the function `ModbusServer::writeInputRegisters` got the following error:

```text
/tmp/ccmQwHO6.ltrans1.ltrans.o: In function `main':
<artificial>:(.text.startup+0x996): undefined reference to `ModbusServer::writeInputRegisters(int, unsigned int*, int)'
collect2: error: ld returned 1 exit status
exit status 1
Error compiling for board Arduino/Genuino Mega or Mega 2560.
```

The function is documented under the official ArduinoModbus library site:
https://www.arduino.cc/en/ArduinoModbus/ModbusServerwriteInputRegisters

However, looking inside the code, the function seems to be defined in `ModbusServer.h`, but not implemented in `ModbusServer.cpp`.

Is there any specific reason for this or is just a lapse?

**Comment by sandeepmistry** [comment]
Hi @jlucas2019,

Thanks for bringing this to our attention!

> Is there any specific reason for this or is just a lapse?

This was just a lapse. I've opened pull request #20 to correct this. It would be great if you could try out the changes and provide your feedback.

**Comment by terrasmart** [comment]
Hello. 

Is the WriteMultipleHoldingRegisters function n.16 (10H) implemented for the ModbusClient Class ?

I don't find it. 

I need to use a 10H function because I have a sensor which accept only functions 03 and 16.
