### ISSUE TITLE
_modbus_rtu_select() chooses insane timeout delays

### ISSUE THREAD

**Issue by cheetor5923** [arduino-libraries/ArduinoModbus#23]
For some reason the timeout for a modbus reply ends up being 1 whole second. I'm using a RTOS on my arduino and since this is talking in a timing sensitive manner it has to be wrapped by disabling the scheduler.... problem is this causes everything else to come to a halt for 1 entire second... 1 second is insanely long at 57600bps 2ms is more than enough.....

**Comment by sandeepmistry** [comment]
Hi @cheetor5923,

Pull request #15 added a `setTimeout` API, does this fit your needs?

**Comment by cheetor5923** [comment]
Hi Sandeep
Yes that works nicely. Thanks for pointing that out.
