### ISSUE TITLE
ModbusRTUClient.read()

### ISSUE THREAD

**Issue by IanKPC** [arduino-libraries/ArduinoModbus#51]
Hopefully someone can point me in the right direction, im probably making this more complicated than it really is.

When a requestform is sent to the slave node, and the client gets a response. Where is that response stored in memory?

**Comment by per1234** [comment]
Hi @IanKPC. Thanks for your interest in the ArduinoModbus library. This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules.

**Comment by IanKPC** [comment]
My apologies, thank you for the quick response.

Have a good day!
