### ISSUE TITLE
library not work in lgt8fx

### ISSUE THREAD

**Issue by jmcastillejo** [arduino-libraries/ArduinoModbus#67]
library not work in logic green mcu LGT8F328P, SSOP20 version. (in LQFP32 version work correct)

I work with board library: https://github.com/dbuezas/lgt8fx

**Comment by per1234** [comment]
Hi @jmcastillejo Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there:

https://forum.arduino.cc/
