### ISSUE TITLE
Example Program Wont Work on Arduino Pro Mini

### ISSUE THREAD

**Issue by shahab0105** [arduino-libraries/ArduinoModbus#7]
Is this not supposed to work with ProMini board? I'm getting the following on serial monitor upon uploading the sketch (https://github.com/arduino-libraries/ArduinoModbus/blob/master/examples/RTU/ModbusRTUServerLED/ModbusRTUServerLED.ino)
serial monitor output:
⸮o

**Comment by sandeepmistry** [comment]
Hi @shahab0105,

I believe the Pro Mini board only has one Serial port so the example won't work out of the box.
